name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY}}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@157.173.218.97 << 'EOF'
            cd /root/repository/rag-pipeline-chatbot
            git pull origin main
            sudo systemctl restart rag-pipeline-chatbot.service
          EOF
